### ISSUE TITLE
after editing the script file, then reboot, the Max_freq is still the same

### ISSUE THREAD

**Issue by CHen-Hua-Luen** [Qengineering/Jover#1]
Thank you for your resources, but i encounter a issue. 
after i executed the
$ sudo cp arch/arm64/boot/Image /boot/Image
$ sudo reboot
command, it succeeded
, But then i edited the script (overclock.sh), then reboot, it failed, Max_freq did not change,
although i executed $ sudo /etc/init.d/overclock.sh  
first, then reboot, still the same.what is the possible reason? Thanks

Before
$ sudo cp arch/arm64/boot/Image /boot/Image
$ sudo reboot
![github1](https://user-images.githubusercontent.com/57308464/121868227-4fc0e580-cd33-11eb-8e81-d3af3ba74453.png)

After
![github2](https://user-images.githubusercontent.com/57308464/121868233-53ed0300-cd33-11eb-9ae0-7c7ed3eb3554.png)

After editing the script file then reboot
![github3](https://user-images.githubusercontent.com/57308464/121868300-66ffd300-cd33-11eb-9ad2-8d20875cc65d.png)

![github4](https://user-images.githubusercontent.com/57308464/121868307-68310000-cd33-11eb-84c1-c6a57ab43c01.png)

**Comment by Qengineering** [comment]
Dear @CHen-Hua-Luen,

The max frequency of the GPU is 99840000 (998.4 MHz). You cannot set the clock any higher. 
As you can see in your screen dump, the CPU clock is lowered to 1.9 GHz. Just as you set in the script.

**Comment by CHen-Hua-Luen** [comment]
thank you
