### ISSUE TITLE
Overclock the GPU to 1.1 GHz

### ISSUE THREAD

**Issue by s0301132** [Qengineering/Jover#2]
Hi, if I want to overclock my GPU to 1.1 GHz, can I change the `tegra210-dvfs.c` like this to achieve it?

```
@@ -768,8 +775,8 @@ static struct cvb_dvfs gpu_cvb_dvfs_table[] = {
 		.speedo_id = 2,
 		.process_id = -1,
 		.pll_min_millivolts = 818,
-		.max_mv = 1150,
-		.max_freq = 998400,
+		.max_mv = 1250,
+		.max_freq = 1102000,
 #ifdef CONFIG_TEGRA_USE_NA_GPCPLL
 		NA_FREQ_CVB_TABLE,
 #else
```

**Comment by Qengineering** [comment]
Dear @s0301132,

You could always try it. However, I doubt if this frequency will be stable in all circumstances. Don't be surprised if it hangs.

**Comment by s0301132** [comment]
Thanks @Qengineering ! now I can overclock my jetson nano to 1.15GHz
